### ISSUE TITLE
None type in preprocess_data.py

### ISSUE THREAD

**Issue by wamiq-reyaz** [nv-tlabs/ATISS#6] opened 2022-01-02 19:59 UTC
Hello,

For some models, the category in the `json` is None, and `preprocess_data.py` does not handle that well, for example I get.

> {'model_id': '00e4b7dd-08a6-4433-a439-856e4b5de58a', 'super-category': 'Others', 'category': None, 'style': 'Minimalist', 'material': 'Composition', 'theme': 'Gold Foil'}

Should this be handled by the blacklists? Or am I doing something wrong?

**Comment by paschalidoud** [comment] 2022-01-21 01:26
Hi @wamiq-reyaz,

I am very sorry for my super late reply! @nazcaspider suggested a fix that should fix this issue. It seems that 3D-FRONT was  updated and now contains some categories that are defined as None. I just committed the fix and hopefully the issue will be resolved.

I am closing the issue for now but please feel free to reopen it in case the issue is not solved.

Cheers,
Despoina

**Closed by paschalidoud** 2022-01-21 01:26 UTC
